class SharedPreferencesConstant {
  // Singleton implementation
  static const SharedPreferencesConstant _instance =
      SharedPreferencesConstant._internal();
  factory SharedPreferencesConstant() {
    return _instance;
  }
  const SharedPreferencesConstant._internal();

  static String saveLanguageKey = 'lang';
  static String financialInstrumentSymbol = 'financialInstrumentSymbol';
  static String financialInstrumentName = 'financialInstrumentName';
  static String length = 'length';
  static String tolerance = 'tolerance';
  static String darkMode = 'darkMode';
  static String isEn = 'isEn';
  static String alwaysShowAnalytics = 'alwaysShowAnalytics';
  static String messages = 'messages';
  static String watchlist = 'watchlist';
  static String alwaysShowSdDistPlot = 'alwaysShowSdDistPlot';
  static String apiKey = 'apiKey';
  static String apiKeyErr = 'apiKeyErr';
  static String jumpServerUrl = 'jumpServerUrl';
  static String alwaysSkipSymbolInSearch = 'alwaysSkipSymbolInSearch';
  static String alwayStrictMatchCriteria = 'alwayStrictMatchCriteria';
  static String alwaysShowMinuteData = 'alwaysShowMinuteData';
  static String subLength = 'subLength';
  static String alwaysMaMatchCriteria = 'alwaysMaMatchCriteria';
  static String alwaysUseCrossData = 'alwaysUseCrossData';
  static String lockTrend = 'lockTrend';

  // static String matchRows = 'matchRows';
  // static String spyMatchRows = 'spyMatchRows';
  // static String qqqMatchRows = 'qqqMatchRows';
  // static String usoMatchRows = 'usoMatchRows';
  // static String gldMatchRows = 'gldMatchRows';
  // static String slvMatchRows = 'slvMatchRows';
  // static String iwmMatchRows = 'iwmMatchRows';
  // static String xlkMatchRows = 'xlkMatchRows';
  // static String aaplMatchRows = 'aaplMatchRows';
  // static String baMatchRows = 'baMatchRows';
  // static String bacMatchRows = 'bacMatchRows';
  // static String mcdMatchRows = 'mcdMatchRows';
  // static String nvdaMatchRows = 'nvdaMatchRows';
  // static String msftMatchRows = 'msftMatchRows';
  // static String gskMatchRows = 'gskMatchRows';
  // static String tslaMatchRows = 'tslaMatchRows';
  // static String amznMatchRows = 'amznMatchRows';
  // static String listCandledata = 'listCandledata';
  // static String spyListCandledata = 'spyListCandledata';
  // static String qqqListCandledata = 'qqqListCandledata';
  // static String usoListCandledata = 'usoListCandledata';
  // static String gldListCandledata = 'gldListCandledata';
  // static String slvListCandledata = 'slvListCandledata';
  // static String iwmListCandledata = 'iwmListCandledata';
  // static String xlkListCandledata = 'xlkListCandledata';
  // static String aaplListCandledata = 'aaplListCandledata';
  // static String baListCandledata = 'baListCandledata';
  // static String bacListCandledata = 'bacListCandledata';
  // static String mcdListCandledata = 'mcdListCandledata';
  // static String nvdaListCandledata = 'nvdaListCandledata';
  // static String msftListCandledata = 'msftListCandledata';
  // static String gskListCandledata = 'gskListCandledata';
  // static String tslaListCandledata = 'tslaListCandledata';
  // static String amznListCandledata = 'amznListCandledata';
  // static String candleListList = 'candleListList';
  // static String spyCandleListList = 'spyCandleListList';
  // static String qqqCandleListList = 'qqqCandleListList';
  // static String usoCandleListList = 'usoCandleListList';
  // static String gldCandleListList = 'gldCandleListList';
  // static String slvCandleListList = 'slvCandleListList';
  // static String iwmCandleListList = 'iwmCandleListList';
  // static String xlkCandleListList = 'xlkCandleListList';
  // static String aaplCandleListList = 'aaplCandleListList';
  // static String baCandleListList = 'baCandleListList';
  // static String bacCandleListList = 'bacCandleListList';
  // static String mcdCandleListList = 'mcdCandleListList';
  // static String nvdaCandleListList = 'nvdaCandleListList';
  // static String msftCandleListList = 'msftCandleListList';
  // static String gskCandleListList = 'gskCandleListList';
  // static String tslaCandleListList = 'tslaCandleListList';
  // static String amznCandleListList = 'amznCandleListList';
  // static String img1Bytes = 'img1Bytes';
  // static String img2Bytes = 'img2Bytes';
  // static String img3Bytes = 'img3Bytes';
  // static String img4Bytes = 'img4Bytes';
  // static String img5Bytes = 'img5Bytes';
  // static String img6Bytes = 'img6Bytes';
  // static String img7Bytes = 'img7Bytes';
  // static String img8Bytes = 'img8Bytes';
  // static String img9Bytes = 'img9Bytes';
  // static String img10Bytes = 'img10Bytes';
}
